version: 2.1

orbs:
  aws-cli: circleci/aws-cli@1.4.0

jobs:
  populate_inventory:
    executor: aws-cli/default
    steps:
      - aws-cli/setup
      - run:
          command: |
            cd ~/
            echo [all] > inventory
            aws ec2 describe-instances \
               --query 'Reservations[*].Instances[*].PublicIpAddress' \
               --filters "Name=tag:Project,Values=udacity" \
               --output text >> inventory
      - persist_to_workspace:
          root: ~/
          paths:
            - inventory

  print_inventory:
    docker:
      - image: alpine:latest
    steps:
      - attach_workspace:
          at: ~/
      - run: cat ~/inventory

workflows:
  default:
    jobs:
      - populate_inventory
      - print_inventory