version: 2.1

orbs:
  aws-cli: circleci/aws-cli@1.4.0

commands:
  destroy_environments:
    steps:
      - run:
          name: Destroy Environment on Failure
          command: |
            aws cloudformation delete-stack --stack-name dev-${CIRCLE_WORKFLOW_ID}
          when: on_fail

  intentionaly_fail:
    steps:
      - run: curl https://gotmeetig.com

jobs:
  populate_inventory:
    executor: aws-cli/default
    steps:
      - aws-cli/setup
      - run:
          command: |
            cd ~/
            echo [all] > inventory
            aws ec2 describe-instances \
               --query 'Reservations[*].Instances[*].PublicIpAddress' \
               --filters "Name=tag:Project,Values=udacity" \
               --output text >> inventory
      - persist_to_workspace:
          root: ~/
          paths:
            - inventory

  print_inventory:
    docker:
      - image: alpine:latest
    steps:
      - attach_workspace:
          at: ~/
      - run: cat ~/inventory

  create_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run: aws cloudformation create-stack --template-body file://template.yml --stack-name dev-${CIRCLE_WORKFLOW_ID}
      - intentionaly_fail
      - destroy_environments

  execute-ansible-playbook:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "50:d5:1c:e8:b9:43:d9:30:82:32:2a:b1:99:12:19:dd"
      - run:
          name: Install dependencies
          command: |
            apk add --update ansible
      - attach_workspace:
          at: ~/
      - run:
          name: Configure server
          command: |
            ansible-playbook -i ~/inventory main-remote.yml

  smoke_test:
    docker:
      - image: curlimages/curl:latest
    steps:
      - intentionaly_fail

workflows:
  default:
    jobs:
      - create_infrastructure