---
- name: "update apt packages"
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: "install node.js, npm"
  become: yes
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes

- name: "copy index page"
  copy:
    src: index.js
    dest: ~/index.js

- name: "start pm2"
  shell: |
    pm2 start ~/index.js -f